spring.application.name=research-assistant
# interation with an AI model
#gemini.api.url = https://generativelanguage.googleapis.com/v1beta/models/gemini-flash-latest:generateContent?key=
gemini.api.url=${GEMINI_API_URL}
gemini.api.key = ${GEMINI_KEY}